! DO NOT EDIT THIS FILE!!!
!
! This file is automatically generated by write_probin.py at
! compile-time.
!
! To add a runtime parameter, do so by editting the appropriate _parameters
! file.

! This module stores the runtime parameters.  The probin_init() routine is
! used to initialize the runtime parameters

module extern_probin_module

  use amrex_fort_module, only: rt => amrex_real

  implicit none

  private

  real (rt), save, public :: eos_gamma = 5.d0/3.d0
  !$acc declare create(eos_gamma)
  logical, save, public :: eos_assume_neutral = .true.
  !$acc declare create(eos_assume_neutral)
  real (rt), save, public :: small_x = 1.d-30
  !$acc declare create(small_x)
  logical, save, public :: use_tables = .false.
  !$acc declare create(use_tables)
  logical, save, public :: use_c12ag_deboer17 = .false.
  !$acc declare create(use_c12ag_deboer17)
  integer, save, public :: ode_max_steps = 150000
  !$acc declare create(ode_max_steps)
  integer, save, public :: scaling_method = 2
  !$acc declare create(scaling_method)
  logical, save, public :: use_timestep_estimator = .false.
  !$acc declare create(use_timestep_estimator)
  real (rt), save, public :: ode_scale_floor = 1.d-6
  !$acc declare create(ode_scale_floor)
  integer, save, public :: ode_method = 1
  !$acc declare create(ode_method)
  real (rt), save, public :: safety_factor = 1.d9
  !$acc declare create(safety_factor)
  logical, save, public :: do_constant_volume_burn = .false.
  !$acc declare create(do_constant_volume_burn)
  logical, save, public :: call_eos_in_rhs = .false.
  !$acc declare create(call_eos_in_rhs)
  real (rt), save, public :: dT_crit = 1.0d20
  !$acc declare create(dT_crit)
  integer, save, public :: burning_mode = 1
  !$acc declare create(burning_mode)
  real (rt), save, public :: burning_mode_factor = 1.d-1
  !$acc declare create(burning_mode_factor)
  logical, save, public :: integrate_temperature = .true.
  !$acc declare create(integrate_temperature)
  logical, save, public :: integrate_energy = .true.
  !$acc declare create(integrate_energy)
  integer, save, public :: jacobian = 1
  !$acc declare create(jacobian)
  logical, save, public :: centered_diff_jac = .false.
  !$acc declare create(centered_diff_jac)
  logical, save, public :: burner_verbose = .false.
  !$acc declare create(burner_verbose)
  real (rt), save, public :: rtol_spec = 1.d-12
  !$acc declare create(rtol_spec)
  real (rt), save, public :: rtol_temp = 1.d-6
  !$acc declare create(rtol_temp)
  real (rt), save, public :: rtol_enuc = 1.d-6
  !$acc declare create(rtol_enuc)
  real (rt), save, public :: atol_spec = 1.d-12
  !$acc declare create(atol_spec)
  real (rt), save, public :: atol_temp = 1.d-6
  !$acc declare create(atol_temp)
  real (rt), save, public :: atol_enuc = 1.d-6
  !$acc declare create(atol_enuc)
  logical, save, public :: retry_burn = .false.
  !$acc declare create(retry_burn)
  real (rt), save, public :: retry_burn_factor = 1.25d0
  !$acc declare create(retry_burn_factor)
  real (rt), save, public :: retry_burn_max_change = 1.0d2
  !$acc declare create(retry_burn_max_change)
  logical, save, public :: abort_on_failure = .true.
  !$acc declare create(abort_on_failure)
  logical, save, public :: renormalize_abundances = .false.
  !$acc declare create(renormalize_abundances)
  real (rt), save, public :: SMALL_X_SAFE = 1.0d-30
  !$acc declare create(SMALL_X_SAFE)
  real (rt), save, public :: MAX_TEMP = 1.0d11
  !$acc declare create(MAX_TEMP)
  real (rt), save, public :: react_boost = -1.d0
  !$acc declare create(react_boost)

end module extern_probin_module

subroutine runtime_init(name,namlen)

  use extern_probin_module

  implicit none

  integer :: namlen
  integer :: name(namlen)

  integer :: un, i, status

  integer, parameter :: maxlen = 256
  character (len=maxlen) :: probin


  namelist /extern/ eos_gamma
  namelist /extern/ eos_assume_neutral
  namelist /extern/ small_x
  namelist /extern/ use_tables
  namelist /extern/ use_c12ag_deboer17
  namelist /extern/ ode_max_steps
  namelist /extern/ scaling_method
  namelist /extern/ use_timestep_estimator
  namelist /extern/ ode_scale_floor
  namelist /extern/ ode_method
  namelist /extern/ safety_factor
  namelist /extern/ do_constant_volume_burn
  namelist /extern/ call_eos_in_rhs
  namelist /extern/ dT_crit
  namelist /extern/ burning_mode
  namelist /extern/ burning_mode_factor
  namelist /extern/ integrate_temperature
  namelist /extern/ integrate_energy
  namelist /extern/ jacobian
  namelist /extern/ centered_diff_jac
  namelist /extern/ burner_verbose
  namelist /extern/ rtol_spec
  namelist /extern/ rtol_temp
  namelist /extern/ rtol_enuc
  namelist /extern/ atol_spec
  namelist /extern/ atol_temp
  namelist /extern/ atol_enuc
  namelist /extern/ retry_burn
  namelist /extern/ retry_burn_factor
  namelist /extern/ retry_burn_max_change
  namelist /extern/ abort_on_failure
  namelist /extern/ renormalize_abundances
  namelist /extern/ SMALL_X_SAFE
  namelist /extern/ MAX_TEMP
  namelist /extern/ react_boost

  eos_gamma = 5.d0/3.d0
  eos_assume_neutral = .true.
  small_x = 1.d-30
  use_tables = .false.
  use_c12ag_deboer17 = .false.
  ode_max_steps = 150000
  scaling_method = 2
  use_timestep_estimator = .false.
  ode_scale_floor = 1.d-6
  ode_method = 1
  safety_factor = 1.d9
  do_constant_volume_burn = .false.
  call_eos_in_rhs = .false.
  dT_crit = 1.0d20
  burning_mode = 1
  burning_mode_factor = 1.d-1
  integrate_temperature = .true.
  integrate_energy = .true.
  jacobian = 1
  centered_diff_jac = .false.
  burner_verbose = .false.
  rtol_spec = 1.d-12
  rtol_temp = 1.d-6
  rtol_enuc = 1.d-6
  atol_spec = 1.d-12
  atol_temp = 1.d-6
  atol_enuc = 1.d-6
  retry_burn = .false.
  retry_burn_factor = 1.25d0
  retry_burn_max_change = 1.0d2
  abort_on_failure = .true.
  renormalize_abundances = .false.
  SMALL_X_SAFE = 1.0d-30
  MAX_TEMP = 1.0d11
  react_boost = -1.d0


  ! create the filename
  if (namlen > maxlen) then
     print *, 'probin file name too long'
     stop
  endif

  do i = 1, namlen
     probin(i:i) = char(name(i))
  end do


  ! read in the namelist
  un = 9
  open (unit=un, file=probin(1:namlen), form='formatted', status='old')
  read (unit=un, nml=extern, iostat=status)

  if (status < 0) then
     ! the namelist does not exist, so we just go with the defaults
     continue

  else if (status > 0) then
     ! some problem in the namelist
     print *, 'ERROR: problem in the extern namelist'
     stop
  endif

  close (unit=un)

  !$acc update &
  !$acc device(eos_gamma, eos_assume_neutral, small_x) &
  !$acc device(use_tables, use_c12ag_deboer17, ode_max_steps) &
  !$acc device(scaling_method, use_timestep_estimator, ode_scale_floor) &
  !$acc device(ode_method, safety_factor, do_constant_volume_burn) &
  !$acc device(call_eos_in_rhs, dT_crit, burning_mode) &
  !$acc device(burning_mode_factor, integrate_temperature, integrate_energy) &
  !$acc device(jacobian, centered_diff_jac, burner_verbose) &
  !$acc device(rtol_spec, rtol_temp, rtol_enuc) &
  !$acc device(atol_spec, atol_temp, atol_enuc) &
  !$acc device(retry_burn, retry_burn_factor, retry_burn_max_change) &
  !$acc device(abort_on_failure, renormalize_abundances, SMALL_X_SAFE) &
  !$acc device(MAX_TEMP, react_boost)

end subroutine runtime_init

